apiVersion: 1

datasources:
  - name: DS_POSTGRES
    type: postgres
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: "postgres"
    jsonData:
      database: postgres
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1200
      timescaledb: false